[package]
name = "codeql-extractor"
version = "0.1.0"
edition = "2021"
authors = ["GitHub"]

[dependencies]
flate2 = "1.0"
tree-sitter = "0.20"
tracing = "0.1"
rayon = "1.5.0"
regex = "1.7.1"
encoding = "0.2"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
num_cpus = "1.14.0"
