# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: /test/.*$(?<!\.ql)(?<!\.qll)(?<!\.qlref)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.1
    hooks:
      - id: clang-format
        files: ^swift/.*\.(h|c|cpp)$

  - repo: local
    hooks:
      - id: codeql-format
        name: Fix QL file formatting
        files: \.qll?$
        language: system
        entry: codeql query format --in-place

      - id: sync-files
        name: Fix files required to be identical
        language: system
        entry: python3 config/sync-files.py --latest
        pass_filenames: false

      - id: qhelp
        name: Check query help generation
        files: \.qhelp$
        language: system
        entry: python3 misc/scripts/check-qhelp.py

      - id: swift-codegen
        name: Run Swift checked in code generation
        files: ^swift/(codegen/|.*/generated/|ql/lib/(swift\.dbscheme$|codeql/swift/elements))
        language: system
        entry: bazel run //swift/codegen
        pass_filenames: false
