[package]
name = "ast-generator"
version = "0.1.0"
edition = "2021"

# When updating these dependencies, run `rust/update_cargo_deps.sh`
[dependencies]
ungrammar = "1.16.1"
proc-macro2 = "1.0.47"
quote = "1.0.20"
either = "1.9.0"
ra_ap_stdx = "0.0.248"
itertools = "0.12.0"
