name: Mark stale issues

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    if: github.repository == 'github/codeql'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 14 days with no activity. Comment or remove the `Stale` label in order to avoid having this issue closed in 7 days.'
        close-issue-message: 'This issue was closed because it has been inactive for 7 days.'
        days-before-stale: 14
        days-before-close: 7
        only-labels: awaiting-response

        # do not mark PRs as stale
        days-before-pr-stale: -1
        days-before-pr-close: -1

        # Uncomment for dry-run
        # debug-only: true
        # operations-per-run: 1000
