name: Check framework coverage changes

on:
  pull_request:
    paths:
      - '.github/workflows/csv-coverage-pr-comment.yml'
      - '*/ql/src/**/*.ql'
      - '*/ql/src/**/*.qll'
      - 'misc/scripts/library-coverage/*.py'
      # input data files
      - '*/documentation/library-coverage/cwe-sink.csv'
      - '*/documentation/library-coverage/frameworks.csv'
    branches:
      - main
      - 'rc/*'

jobs:
  generate:
    name: Generate framework coverage artifacts

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github.event) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Clone self (github/codeql) - MERGE
      uses: actions/checkout@v2
      with:
        path: merge
    - name: Clone self (github/codeql) - BASE
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.sha }}
        path: base
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Download CodeQL CLI
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         gh release download --repo "github/codeql-cli-binaries" --pattern "codeql-linux64.zip"
    - name: Unzip CodeQL CLI
      run: unzip -d codeql-cli codeql-linux64.zip
    - name: Generate CSV files on merge and base of the PR
      run: |
        echo "Running generator on ${{github.sha}}"
        PATH="$PATH:codeql-cli/codeql" python merge/misc/scripts/library-coverage/generate-report.py ci merge merge
        mkdir out_merge
        cp framework-coverage-*.csv out_merge/
        cp framework-coverage-*.rst out_merge/

        echo "Running generator on ${{github.event.pull_request.base.sha}}"
        PATH="$PATH:codeql-cli/codeql" python base/misc/scripts/library-coverage/generate-report.py ci base base
        mkdir out_base
        cp framework-coverage-*.csv out_base/
        cp framework-coverage-*.rst out_base/
    - name: Upload CSV package list
      uses: actions/upload-artifact@v2
      with:
        name: csv-framework-coverage-merge
        path: |
          out_merge/framework-coverage-*.csv
          out_merge/framework-coverage-*.rst
    - name: Upload CSV package list
      uses: actions/upload-artifact@v2
      with:
        name: csv-framework-coverage-base
        path: |
          out_base/framework-coverage-*.csv
          out_base/framework-coverage-*.rst
    - name: Save PR number
      run: |
        mkdir -p pr
        echo ${{ github.event.number }} > pr/NR
    - name: Upload PR number
      uses: actions/upload-artifact@v2
      with:
        name: pr
        path: pr/

