name: Generate CodeQL documentation using Sphinx

on:
  push:
    branches:
     - main
     - 'rc/**'
     - 'lgtm.com'
  pull_request:
    paths:
      - 'docs/language/query-help/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone github/codeql
      uses: actions/checkout@v2
      with:
        path: codeql 
    - name: Clone github/codeql-go
      uses: actions/checkout@v2
      with:
        repository: 'github/codeql-go'
        path: codeql-go
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Download CodeQL CLI
      uses: dsaltares/fetch-gh-release-asset@aa37ae5c44d3c9820bc12fe675e8670ecd93bd1c
      with:
        repo: "github/codeql-cli-binaries"
        version: "latest"
        file: "codeql-linux64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Unzip CodeQL CLI
      run: unzip -d codeql-cli codeql-linux64.zip
    - name: Set up query help docs folder  
      run: |
        cp -r codeql/docs/language/query-help/ . ; cp -r codeql/docs/language/global-sphinx-files/ .
    - name: Query help to markdown
      run: |
        PATH="$PATH:codeql-cli/codeql" python codeql/docs/language/query-help-markdown.py
  #  - name: Run Sphinx for query help
  #    uses: ammaraskar/sphinx-action@master
  #    with:
  #      docs-folder: "query-help/"
  #      pre-build-command: "python -m pip install --upgrade recommonmark"
  #      build-command: "sphinx-build -b html . _build" 
    - name: Check docs folder postscript 1
      working-directory: '${{ github.workspace }}/query-help'  
      run: ls -la  
  #  - name: Check docs folder postscript 2
  #    working-directory: '${{ github.workspace }}/query-help/_build'  
  #    run: ls -la 
    #- name: Upload HTML artifacts
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: query-help-html
    #    path: query-help/_build
    
