name: JS ML-powered queries tests

on:
  push:
    paths:
      - "javascript/ql/experimental/adaptivethreatmodeling/**"
      - .github/workflows/js-ml-tests.yml
      - .github/actions/fetch-codeql/action.yml
      - codeql-workspace.yml
    branches:
      - main
      - "rc/*"
  pull_request:
    paths:
      - "javascript/ql/experimental/adaptivethreatmodeling/**"
      - .github/workflows/js-ml-tests.yml
      - .github/actions/fetch-codeql/action.yml
      - codeql-workspace.yml
  workflow_dispatch:

defaults:
  run:
    working-directory: javascript/ql/experimental/adaptivethreatmodeling

jobs:
  qlcompile:
    name: Check QL compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/fetch-codeql

      - name: Install pack dependencies
        run: |
          for pack in modelbuilding src; do
            codeql pack install --mode verify -- "${pack}"
          done
      
      - name: Cache compilation cache
        id: query-cache
        uses: ./.github/actions/cache-query-compilation
        with: 
          key: js-ml-compilation

      - name: Check QL compilation
        run: |
          codeql query compile \
            --check-only \
            --ram 5120 \
            --additional-packs "${{ github.workspace }}" \
            --threads=0 \
            --compilation-cache "${{ steps.query-cache.outputs.cache-dir }}" \
            -- \
            lib modelbuilding src

  qltest:
    name: Run QL tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/fetch-codeql

      - name: Install pack dependencies
        run: codeql pack install -- test

      - name: Cache compilation cache
        id: query-cache
        uses: ./.github/actions/cache-query-compilation
        with: 
          key: js-ml-tests

      - name: Run QL tests
        run: |
          codeql test run \
            --threads=0 \
            --ram 5120 \
            --additional-packs "${{ github.workspace }}" \
            --compilation-cache "${{ steps.query-cache.outputs.cache-dir }}" \
            -- \
            test
