name: "Swift: Run QL Tests"

on:
  pull_request:
    paths:
      - "swift/**"
      - .github/workflows/swift-qltest.yml
    branches:
      - main
defaults:
  run:
    working-directory: swift

jobs:
  qlformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/fetch-codeql
      - name: Check QL formatting
        run: find ql "(" -name "*.ql" -or -name "*.qll" ")" -print0 | xargs -0 codeql query format --check-only
  qltest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : [ubuntu-20.04, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/fetch-codeql
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Build Swift extractor
        run: |
          bazel run //swift:create-extractor-pack
      - name: Run QL tests
        run: |
          codeql test run --threads=0 --ram 5000 --search-path "${{ github.workspace }}/swift/extractor-pack" --check-databases --check-unused-labels --check-repeated-labels --check-redefined-labels --check-use-before-definition ql/test
        env:
          GITHUB_TOKEN: ${{ github.token }}
